# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos850-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a12s m12,$(TARGET_DEVICE)),)

endif
